# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ls": "01_utils.ipynb",
         "Path.ls": "00_dup_finder.ipynb",
         "Path.lf": "00_dup_finder.ipynb",
         "Path.ld": "00_dup_finder.ipynb",
         "ls_print": "01_utils.ipynb"}

modules = ["dup_finder.py"]

doc_url = "https://ayasyrev.github.io/dup_finder/"

git_url = "https://github.com/ayasyrev/dup_finder/tree/master/"

def custom_doc_links(name): return None
