# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_utils.ipynb (unless otherwise specified).

__all__ = ['ls', 'ls_print', 'ls', 'ls_print']

# Cell
#hide
import datetime, hashlib, os, sys, time, shutil
from pathlib import Path
# from shutil import copyfile, copytree, move, rmtree

# Cell
ls = lambda x: list(x.iterdir())
Path.ls = ls
Path.lf = lambda x: [i for i in x.iterdir() if i.is_file()]
Path.ld = lambda x: [i for i in x.iterdir() if i.is_dir()]

# Cell
def ls_print(path):
    print(path)
    for i in os.scandir(path):
        print('|____', i.name)

# Cell
#hide
import datetime, hashlib, os, sys, time, shutil
from pathlib import Path

from .prepare_test_data import TEST_DATA_PATH, TEST_ROOT, PACKAGE_ROOT, LIB_ROOT

# from shutil import copyfile, copytree, move, rmtree

# Cell
ls = lambda x: list(x.iterdir())

# Cell
def ls_print(path):
    print(path)
    for i in os.scandir(path):
        print('|____', i.name)